# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

future: false
show_drafts: false
static: http://static.dita.io/travel
disqus: travelditaio
url: http://travel.dita.io
analytics: 822e336b242f4e40adfd260bcd2dd6c4 
